### ISSUE TITLE
Block support

### ISSUE THREAD

**Issue by JiriTrecak** [delba/Tactile#3]
Hello,

first, very nice work indeed. What would help this project to be really great is if the methods offered block version instead of target. That way you would be able to do following:

```
view.on(tap) {
    // Do something
}
```

Which removes the decoupling - the need to have different method somewhere else in the code.

Thanks for your time doing this library!

Sincerely,
Jiri

**Comment by delba** [comment]
Hey @JiriTrecak,

Tactile already supports this :smile: 

All of the followings are equivalent:

**1.**

``` swift
view.on(tap, tapped)

// ...

func tapped(tap: UITapGestureRecognizer) {
    print(tap)
}
```

**2.**

``` swift
let tapped = { (tap: UITapGestureRecognizer) -> Void
    print(tap)
}

view.on(tap, tapped)
```

**3.**

``` swift
view.on(tap) { print($0) }
```

Note that you can also use the [shorthand methods](https://github.com/delba/Tactile#the-shorthand-methods):

``` swift
view.tap { print($0) }
```

**Comment by JiriTrecak** [comment]
Man am I dumb today! Thanks, and sorry :) (maybe would be nice to highlight it more in the docs)

**Comment by delba** [comment]
Ahaha no problem! Thanks for Laurine btw :pray:
