### ISSUE TITLE
Testing Tactile methods

### ISSUE THREAD

**Issue by kalmurzayev** [delba/Tactile#6]
Hi! What is the best way to test logic passed to `.tap()` or `.pinch()` methods? How to programmatically trigger those callbacks?

**Comment by delba** [comment]
Hi @kalmurzayev ! The `pinch` and `tap` methods are just creating vanilla `UIPinchGestureRecognizer` and `UITapGestureRecognizer` under the hood.
You can trigger them in tests to check the callbacks are called (see https://medium.com/@borutt/unit-testing-gesture-recognizers-b55444884864 for instance)
